### ISSUE TITLE
Check newline in `mdox-exec` output

### ISSUE THREAD

**Issue by saswatamcode** [bwplotka/mdox#67]
Some commands do not append a newline character by default, for example, `cat`, 
So a file like this which also doesn't have a new line at the end,
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: grafana
spec:
  ingress:
  - ports:
    - port: 3000
      protocol: TCP
  podSelector:
    matchLabels:
      app: grafana
```
is formatted like this
```
```yaml mdox-exec="cat test.yaml"
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: grafana
spec:
  ingress:
  - ports:
    - port: 3000
      protocol: TCP
  podSelector:
    matchLabels:
      app: grafana```
```
Might need to check output of command for newline.
